import os
import requests
import json

# Fetch environment variables
api_key = os.environ.get("GEMINI_API_001KEY")
concept_file = "core_concept.md"
output_file = "lyrics/03_gemini_version.md"

if not api_key:
    print("Error: GEMINI_API_001KEY is not set.")
    exit(1)

# Read your core concept
with open(concept_file, "r", encoding="utf-8") as f:
    core_concept = f.read()

# Construct the prompt for Gemini
prompt = f"""
You are a professional hip-hop/rap lyricist. Read the following core concept file and write a brand new song version.
Include Verse 1, Pre-Chorus, Chorus (Hook), Verse 2, and an Outro. Focus on internal rhymes and a moody, atmospheric vibe.

Core Concept:
{core_concept}
"""

# Gemini API Endpoint (using Gemini 1.5 Flash / Gemini 2.5 Flash architecture)
url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={api_key}"

headers = {"Content-Type": "application/json"}
data = {"contents": [{"parts": [{"text": prompt}]}]}

# Request to Gemini
response = requests.post(url, headers=headers, json=data)

if response.status_code == 200:
    result = response.json()
    lyrics = result["candidates"][0]["content"]["parts"][0]["text"]
    
    # Ensure lyrics folder exists
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    
    # Save the generated lyrics
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(lyrics)
    print("Lyrics successfully generated by Gemini!")
else:
    print(f"API Error: {response.status_code}")
    print(response.text)
    exit(1)
